version: '3.8'

services:
  web:
    build: .
    image: fastapi_teste_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    environment:
      - ENV_FILE=.env.docker
      - WATCHFILES_FORCE_POLLING=true
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: cadastro-de-projetos-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password-projetos
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
